<?php

namespace TaskMngBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function findAllTasksOfUser($userId)
    {
        $result = $this->getEntityManager()
            ->createQuery('SELECT t FROM TaskMngBunde:Task t WHERE t.user_id > :userId')
            ->setParameter('userId', $userId)
            ->getResult();

        return $result;
    }
}
